"""empty message

Revision ID: 204c1ae6144c
Revises: 8d94fde806d9
Create Date: 2025-04-05 13:17:54.824883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '204c1ae6144c'
down_revision = '8d94fde806d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_title', sa.String(length=500), nullable=False))
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['course_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('course_code',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('course_title')

    # ### end Alembic commands ###
