"""empty message

Revision ID: 32c7755c74b8
Revises: 0f4ba60c4efb
Create Date: 2025-03-31 05:17:08.568658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '32c7755c74b8'
down_revision = '0f4ba60c4efb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instructor_id', sa.String(length=50), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_level', sa.String(length=10), nullable=False),
    sa.Column('lecture_start', sa.DateTime(), nullable=False),
    sa.Column('lecture_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_code')
    )
    op.create_table('nonce',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nonce')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('patientID')

    op.drop_table('patients')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('barcode')

    op.drop_table('transactions')
    op.drop_table('labtests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labtests',
    sa.Column('test_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('testType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('testBottleType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('testName', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('testmnemonics', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('testDetails', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('testTAT', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('testPrice', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('test_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('transactions',
    sa.Column('transaction_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CurrentpatientID', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('barcode', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('fullName', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('regtype', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('sex', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('billto', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('testspriority', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('testscheduletype', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('subtotal', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('discount', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('equalltax', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('total', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('paymentmethod', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('payment', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('referenceOrchange', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('sessionconfirm', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('paymentconfirm', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('cashier', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('invoicemnemonics', mysql.VARCHAR(length=2100), nullable=True),
    sa.Column('invoicetestname', mysql.VARCHAR(length=2100), nullable=True),
    sa.Column('invoiceprice', mysql.VARCHAR(length=2100), nullable=True),
    sa.Column('invoicetat', mysql.VARCHAR(length=2900), nullable=True),
    sa.Column('transactTime', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('phlebotomy_processed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('paymentupdateamount', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('paymentupdateby', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('paymentupdateTime', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('transaction_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('barcode', ['barcode'], unique=True)

    op.create_table('patients',
    sa.Column('patient_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patientFirstname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientLastname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientMiddlename', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientSex', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientTitle', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('ageGrade', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientDateofBirth', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientStatus', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientType', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientID', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientEmail', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientAltEmail', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientPhonenumber', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientAltPhonenumber', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientwhatsappnumber', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientAddress', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCity', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientState', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCountry', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientpersonalEnroledby', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCompanyname', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCorporateContactperson', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCorporateEmail', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientAltCorporateEmail', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCorporatePhone', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCorporateAltPhone', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCorporatewhatsappnumber', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCorporateAddress', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCorporateCity', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCorporateState', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCorporateCountry', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('patientCorporateEnroledby', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('enrolment_Time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('patient_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('patientID', ['patientID'], unique=True)

    op.drop_table('nonce')
    op.drop_table('course')
    op.drop_table('attendance')
    # ### end Alembic commands ###
