"""empty message

Revision ID: 8d94fde806d9
Revises: 2dc9636c001f
Create Date: 2025-04-05 13:17:10.846864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d94fde806d9'
down_revision = '2dc9636c001f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.alter_column('course_code',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.drop_index('course_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index('course_code', ['course_code'], unique=True)
        batch_op.alter_column('course_code',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
